project:
  type: book
  output-dir: docs

book:
  title: "Índice de Vulnerablidad Social"
  author: "Bioing. Betsaida López, Bioing. Laura González, Dr. Gener Avilés R"
  date: "1/27/2025"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - antecedentes.qmd
    - objetivo.qmd
    - datos.qmd
    - metodo.qmd
    - result.qmd
    - references.qmd

bibliography: references.bib
csl: ieee.csl

format:
  html:
    theme: darkly
    css: styles.css
